modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
# The modid of the mod
modId="verdure" #mandatory
version="${file.jarVersion}"
displayName="Verdure" #mandatory
logoFile="verdure.png" #optional
credits="Drig for art"
authors="DoltHHaven, Drigonis" #optional
description='''
Minecraft? yes. Minecraft.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.verdure]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.verdure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.verdure]]
modId = "blueprint"
mandatory = true
versionRange = "[6.1.0,)"
ordering = "AFTER"
side = "BOTH"
